G-Node/GCA-Web

app/Global.scala, app/conf/Global.scala, app/utils/GCAAuth.scala, conf/application.conf, test/TestAll.scala, test/controller/AbstractsCtrlTest.scala, test/controller/BaseCtrlTest.scala, test/controller/ConferenceCtrlTest.scala, test/controller/FigureCtrlTest.scala
Handle all errors inside the `conf.Global` object.
This solves #229
=> Unified exception handling in Global

app/views/template.scala.html, build.sbt, project/plugins.sbt, public/javascripts/lib/astate.js, public/javascripts/lib/models.js
Dependencies are now handled vie web-jars. Except `mathjax` which is not in the repo.
This should fix #223
The next step is now to make them available via require js (#225)
=> Use web-jars for client side dependencies

app/assets/javascripts/editor.js
Sometimes when a figure is removed from an abstract, the client side does not properly refresh the abstract data, leading to a display of the already deleted figure.
This behavior is due to caching of ajax requests. Adding "cache: false" to ajax requests fixes this issue.
Therefore "cache: false" has been added to all ajax requests in the abstract editor script.
=> removeAjaxCache: add cache: false to all abstract editor ajax calls

app/assets/javascripts/editor.js, app/assets/stylesheets/layout.less, app/views/submission.scala.html
Some changes to potentially unconfuse users
- show the save button only when an abstract has not been saved before, otherwise all changes are saved automatically anyway
- specify info texts describing what a user can and cannot do when the abstract is in a specifc state
- style these info texts to make them distinguishable from alerts
- display edit buttons only when an abstract is unsaved or in states 'InPreparation' or 'InRevision'
=> Tweak abstract editor

app/models/Abstract.scala, app/models/Account.scala, app/models/Conference.scala
Schema changes for all issues described in #309 
All changes are applied to the existing schema when GCA is started with `jpa.default=defaultPersistenceUnit`. 
Since newly created columns contain only `NULL`  entries the this [script](https://gist.github.com/stoewer/368fad64b2e299d38d9e) can be used to fill them with meaningful values.
=> Schema changes for #309

app/assets/javascripts/editor.js, app/assets/stylesheets/layout.less, app/models/Abstract.scala, app/models/Conference.scala, app/models/Figure.scala, app/models/Model.scala, app/models/Reference.scala, app/views/dashboard/admin/conference.scala.html, app/views/submission.scala.html
The maxlength of all Textfields and Textareas should automatically depend on the size of the corresponding database column.
- Added methods to Model.scala to retrieve the length of a Column from the field of a specific Backend model e.g. Conference or Abstract.
- Updated the Textfields and Textareas in all templates to use the Column size of the corresponding database fields as maxlength.
- Removed static text "(up to 2000 characters)" from style sheet.
- Updated methods to calculate remaining Textarea characters for abstract text and acknowledgements in editor.js to use the corresponding maxlength value from the submission template.
- Tested all field lengths with Abstract create/edit and Conferences create/edit.
Resolves issue #293
Resolves issue #312
=> Update field lengths

app/controllers/Authentication.scala
Fixes redirection to Internal server error, when a non existent email is used for login. 
Fixes Issue #323
=> Login: Fix invalid user error

app/conf/Global.scala
Pages dependent on results from a database query e.g. Abstracts or Conferences now redirect to "Not found - 404" instead of "Internal server error - 500" if the query returns a NoResultsException.
Fixes issue #290
=> Display "Not found - 404" for NoResultExceptions

app/assets/javascripts/admin-conference.js, app/assets/javascripts/lib/models.js, app/controllers/api/Conferences.scala, app/views/dashboard/admin/conference.scala.html, test/controller/ConferenceCtrlTest.scala
- Added conference field geo to the jsModel
- Added GET and PUT methods to admin-conference.js
- Added geo textarea to the view, textarea and upload button are only visible, if the conference already exists.
- Conference controller getGeo now returns an error message, if no geo entry exists for a conference instead of just "error": "true".
This pull request closes issue #303.
=> Front end: Add map information to conference

app/assets/javascripts/editor.js, app/assets/javascripts/lib/astate.js, app/conf/Global.scala, app/models/AbstractState.scala, app/service/AbstractService.scala, app/views/components/owned.scala.html, app/views/dashboard/admin/conference.scala.html, app/views/submission.scala.html, test/controller/AbstractsCtrlTest.scala, test/service/AbstractServiceTest.scala
Issue addressed:
- #143 show state log in editor
- #159 state changes are all done via the state api now
- #307 remove reactivate, add unlock
It moves the withdrawn button to the button into the nav bar at the bottom.
There is quite a bit of ui changes that could still be done, but the PR is quite big as is.
=> [editor] state workflow rework

app/models/Conference.scala, test/controller/ConferenceCtrlTest.scala
Saving a conference without a short description lead to an internal server error at the main page.
- Changed Conference short model column to not null.
- Added a create conference test without name.
- Added a create conference test without short.
This pull request closes Issue #330.
=> Fix create conference missing short error

app/views/dashboard/admin/conference.scala.html
Saving groups before a conference was saved lead to an error. This mini pull request removes this temptation by hiding the group element from unsaved conferences.
This pull request closes Issue #325
=> View: Fix Create conferences group save bug

app/assets/javascripts/editor.js
I decided to have the box there but color it white/transparent if the abstract is not saved. The reason
for having it, also for unsaved abstracts, is that otherwise we cannot actually explain the validation
field in the help text; and I am sure lots of people would miss that the help box text changed after
some form of interaction with the editor.
=> Small changes to validation status badge/button

app/utils/RoutesResolver.scala
Makes it possible to use the docker container with an different address then localhost.
=> Use baseUrl from env (GCA_BASEURL), if available

Dockerfile, startup.sh
The changes to the docker file including the added entry point script enable providing a config file from outside the container.
=> [docker] Provide config from container outside

app/assets/javascripts/abstract-list.js, app/assets/javascripts/abstracts-favourite.js, app/assets/stylesheets/layout.less, app/controllers/Application.scala, app/controllers/api/Abstracts.scala, app/controllers/api/Conferences.scala, app/models/Abstract.scala, app/models/Account.scala, app/service/AbstractService.scala, app/service/ConferenceService.scala, app/utils/RoutesResolver.scala, app/utils/serializer.scala, app/views/abstractlist.scala.html, app/views/dashboard/favouriteabstracts.scala.html, app/views/template.scala.html, conf/routes, test/service/Assets.scala, test/util/serializer/SerializerTest.scala
The favourite abstracts functionality. The three commits show three different parts:
The frontend functionality listing "favourite" abstracts still using the owners property.
The extension of the favUsers/favAbstracts properties.
The front+backend ability to like/dislike abstracts.
Currently the "favourite" button is only available in the selected abstract mode of the abstract-list view.
=> Temp master new

app/assets/javascripts/admin-conference.js, app/assets/javascripts/editor.js, app/service/ConferenceService.scala, app/views/dashboard/admin/conference.scala.html, app/views/template.scala.html
This PR fixes some error messages and issues arising with conference settings and abstracts.
Fixes
- Favourite abstracts are now correctly listed. Closes #431.
- External link icon for the conference home button in the navigation bar. Closes #446.
- A warning message is displayed, if the abstract length is reduced in the conference settings. Closes #427. 
- Non numerical input in the conference settings for 'maximum abstract length' and 'number of figures' is suppressed. Related to issue #426.
- Abstracts saving and submission is possible, if no topics are defined for a conference. Fixes #443.
=> Conference Settings and Astract issues

CHANGELOG.md, app/assets/javascripts/editor.js, app/assets/javascripts/lib/models.js, app/service/AbstractService.scala, app/views/signup.scala.html
This PR
- fixes not displayed error messages on the abstract submission page, see issue #438.
- fixes a submission page JavaScript crash if a reference contains an empty DOI.
- Updates info messages on the abstract submission page; closes #228.
- Now uses the `abstract.isOwner` method in all `AbstractService.scala` methods to address the elusive issue #430.
- The signup page now features links to "Terms of Use" and "Datenschutz".
- fixes the validation result display on the abstract submission page if no topics or preferences are available. Closes #453.
=> Issue fixes B for release 2019

app/assets/stylesheets/layout.less, app/views/abstractlist.scala.html, app/views/dashboard/favouriteabstracts.scala.html
This PR updates some of the favourite abstract style features:
- the message when a user has no favourite abstracts has been slightly changed.
- the favour / unfavour button now come in less intense colors.
- the favour / unfavour button now uses the proper link mouse icon when hovering over.
- the favour / unfavour button now feature a tooltip elaborating on favourite abstracts. Closes #420.
=> Favourite abstract style updates

app/assets/javascripts/abstract-list.js, app/assets/javascripts/admin-abstracts.js, app/controllers/api/Abstracts.scala, app/service/AbstractService.scala, app/views/abstractlist.scala.html, app/views/dashboard/admin/abstracts.scala.html, conf/routes, test/controller/AbstractsCtrlTest.scala, test/service/AbstractServiceTest.scala
With this pull request 
- stars will be shown in the conference abstract list, indicating favourite abstracts of an user. Closes issue #419.
- the favour/disfavour abstract methods in abstract-list.js will only use javascript.
- the string length of notes when changing abstract states will be limited to 255 to avoid database problems. Closes issue #448.
=> Favourite Abstracts Conference List

app/controllers/api/Abstracts.scala, app/service/AbstractService.scala, test/controller/AbstractsCtrlTest.scala, test/service/AbstractServiceTest.scala
This pull request adds tests for functions in Abstracts controller und AbstractService used for the favourite abstracts functionality as well as some minor changes to these functions, not changing the funtionality of them. The isFavourite routine is deleted, as it was replaced.
=> Favourite Abstracts Tests

app/assets/javascripts/conference-list.js, app/controllers/api/Banners.scala
This PR introduces two minor banner upload fixes and closes #385:
- now both conference and site admin are able to upload banners via the conference administration.
- fixes the small issue that conference thumbnails on the main conference listing page were incorrectly shifted to another conference, if a non-active, non-published conference was in the conference list.
=> Minor banner upload fixes

build.sbt, project/plugins.sbt
This PR is a hotfix for issue #497.
The build time is dramatically increased since the build tool still tries to fetch all dependencies from the `http` maven repository first and fails before moving on to the additionally provided functional URL.
=> Hotfix Maven project build issue

app/views/conferencelist.scala.html, app/views/dashboard/admin/conference.scala.html, test/frontend/Cookies.py, test/frontend/Readme.md, test/frontend/conftest.py, test/frontend/load_cookies.py, test/frontend/test_conference_creation.py
This PR
- Introduces functions for frontend tests that include scrolling for Firefox for click(), send_keys() and get_attribute()
- Adds conference creation tests for all fields that don't require uploading.
- Includes frontend look-ups to check, whether the filling in of the conference settings form works correctly and changes are shown in the non-admin frontend.
- Adds unpublished, non-active conferences to the admins conference list, marked by an "Unpublished"-tag. Closes #500 
- Adds some remarks about writing tests to the selenium-tests read.me
- Removes the selenium jar, as users should download the newest version for themselves
- Replaces the cookies.json with direct admin login for frontend tests
=> Conference Creation Tests

CHANGELOG.md, app/assets/javascripts/lib/models.js, app/assets/javascripts/locations.js, app/assets/stylesheets/custom/bootstrap/_custom-print.less, app/assets/stylesheets/g-node-bootstrap-print.play.less, app/views/conferencelist.scala.html, app/views/template.scala.html, doc/json_examples/locations.json, doc/json_examples/schedule.json, patch/patch_v1_2_to_v1_3.sql
This PR adds a couple of fixes and updates:
- print view specific stylesheets are added for useful print rendering of abstract pages. Closes #508.
- an issue was resolved where thumbnails on the main page where not properly scaled.
- an issue was resolved where the "unlisted conferences" title was displayed to non-admin users. Closes #500.
- the mapbox.js plugin was outdated, this PR updates it to the latest version. Closes #510.
- an issue was resolved where the sortid of an abstract was removed when an abstract was re-submitted. Closes issue #507.
=> Fixes and updates

CHANGELOG.md, Readme.md, app/controllers/Application.scala, app/views/components/mathjax.scala.html, app/views/mob_template.scala.html, app/views/template.scala.html, public/service-worker.js, test/frontend/Readme.md, test/frontend/test_conference_creation.py, test/frontend/test_editor.py, test/frontend/test_login.py
This PR introduces a major rewrite of the frontend selenium tests.
- it introduces a fix for the conference settings tests where it was possible, that the wrong conference was accessed leading to failing tests.
- the rewrite also aims to restructure these tests to increase readability and adds comments to make extensive tests more easily understandable.
- the frontend setup and test documentation is rewritten and now also linked from the main readme document.
The PR also
- updates the mathjax.js dependency to version 2.7.7 closing issue #506.
- makes the copyright date dynamic.
=> Frontend tests
