G-Node/GCA-Web

.gitignore, app/service/ConferenceService.scala
works for both MySQL / Postgres
=> Patch to fix abstracts loading speed

app/assets/stylesheets/layout.less, app/views/submission.scala.html
=> Improve affiliation assignment

app/conf/Global.scala, app/controllers/Authentication.scala, app/forms/SignInForm.scala, app/service/AccountStore.scala, conf/routes, test/controller/BaseCtrlTest.scala
Should be able to successfully authenticate again.
All tests seem to work, except one.
=> Part II of Authentication via Silhouette

app/views/template.scala.html, build.sbt
Somehow the knockout (same version) from the web-jars is not working. This pr changes it back to the cdn version.
=> Small fix that makes the editor work again

app/assets/javascripts/editor.js, app/controllers/api/Figures.scala, app/views/submission.scala.html, conf/routes, test/controller/FigureCtrlTest.scala
=> Separate editing of figure and caption #220

app/models/Account.scala, app/plugins/DBUtil.scala, test/service/Assets.scala
Seems like it's working if one explicitly assigns Account to the CredentialsLogin.
But I'd appreciate if you double check.
Thanx
=> JPA threading temp fix - option 1 (always new EM)

app/assets/javascripts/editor.js, app/views/submission.scala.html
First step to resolve issue 125
- rewrote all modals to use header, body and footer templates
- tested create new abstract and edit abstract with firefox and chrome
=> Modal templates

app/controllers/Accounts.scala, app/controllers/api/Accounts.scala, app/service/AccountStore.scala, test/service/AccountStoreTest.scala
Without confirmation mail and tests
=> Accounts: first working draft for signup

app/assets/javascripts/admin-conference.js, app/assets/javascripts/main.js, app/conf/Global.scala, app/models/Conference.scala, app/views/dashboard/admin/conference.scala.html, app/views/error/InternalServerError.scala.html, app/views/template.scala.html
Add a datetime picker for conference admin page (issue #162)
Better error handling, i.e. not just "Internal Server Error" for
IO errors.
=> Conference admin page error and datepicker

app/assets/javascripts/admin-conference.js, app/assets/javascripts/lib/models.js, app/models/Conference.scala, app/utils/serializer.scala, app/views/dashboard/admin/conference.scala.html, app/views/template.scala.html, test/service/Assets.scala
=> Support for smart App banners for iOS

app/assets/javascripts/admin-conference.js, app/assets/javascripts/lib/models.js, app/controllers/Application.scala, app/models/Conference.scala, app/utils/serializer.scala, app/views/conferencelist.scala.html, app/views/dashboard/admin/conference.scala.html, app/views/submission.scala.html, test/service/Assets.scala, test/service/ConferenceServiceTest.scala, test/util/serializer/SerializerTest.scala
=> Active switch and configurable presentation preferences

.gitignore, app/models/Model.scala, app/service/AbstractService.scala, app/service/FigureService.scala
* Closes issue #289 
* Fixes also another bug related to abstract changes made by the conference owner
=> Conference owner can now change abstract state

app/assets/javascripts/editor.js
=> Check for warnings before accepting submission

app/assets/javascripts/lib/models.js, app/assets/stylesheets/layout.less, app/utils/serializer.scala, app/views/components/singleabstract.scala.html, app/views/conference.scala.html, app/views/conferencelist.scala.html, app/views/dashboard/admin/accounts.scala.html
Small changes related to the following issues: #287, #291, #294, #296 and #298
=> A couple of small fixes (mostly UI related)

app/models/Conference.scala, app/views/conference.scala.html, app/views/conferencelist.scala.html
=> conference: smarter date formatting

app/service/AbstractService.scala, app/service/util/PermissionsBase.scala
=> Adding owner to abstract

test/controller/ConferenceCtrlTest.scala
Removed checks that were H2 database specific.
=> Bug: Fix postgres create conference fail

app/assets/javascripts/admin-conference.js, app/assets/javascripts/lib/models.js, app/controllers/api/Conferences.scala, app/models/Conference.scala, app/service/ConferenceService.scala, app/utils/serializer.scala, app/views/dashboard/admin/conference.scala.html, conf/routes, test/controller/ConferenceCtrlTest.scala, test/service/Assets.scala, test/service/ConferenceServiceTest.scala, test/util/serializer/SerializerTest.scala
=> Conference grouping

app/assets/javascripts/abstract-viewer.js, app/assets/javascripts/admin-accounts.js, app/assets/javascripts/editor.js, app/assets/javascripts/lib/msg.js, app/views/abstractviewer.scala.html, app/views/components/messsagebox.scala.html, app/views/dashboard/admin/accounts.scala.html, app/views/submission.scala.html
=> [editor] help/info text rework and restyle

app/assets/stylesheets/layout.less, app/views/conference.scala.html, app/views/conferencelist.scala.html, app/views/dashboard/admin/conference.scala.html, app/views/template.scala.html
=> Admintabs, conf. (list) style, jumbotron styles

.gitignore
This should make life easier for our admins
=> gitignore: files to ignore in production

app/controllers/api/Abstracts.scala, app/controllers/api/Conferences.scala, app/models/Abstract.scala, app/models/Conference.scala, app/models/Tagged.scala, app/service/AbstractService.scala, app/service/ConferenceService.scala, test/controller/AbstractsCtrlTest.scala, test/controller/ConferenceCtrlTest.scala, test/service/AbstractServiceTest.scala, test/service/Assets.scala, test/service/ConferenceServiceTest.scala
Part of #354. Should solve #353.
=> Initial eTag support

app/models/Abstract.scala, app/models/Conference.scala, app/service/AbstractService.scala, app/service/ConferenceService.scala, app/service/FigureService.scala, test/controller/AbstractsCtrlTest.scala, test/controller/ConferenceCtrlTest.scala
=> Update mtime for indirect abstract, conference updates

app/views/components/singleabstract.scala.html
=> Changed ordering of colon and figure number in abstract view

app/assets/javascripts/abstract-list.js, app/assets/javascripts/abstract-viewer.js, app/assets/javascripts/conference-schedule.js, app/assets/javascripts/lib/offline.js, app/assets/javascripts/lib/update-storage.js, app/assets/javascripts/locations.js, app/assets/javascripts/main.js, app/views/template.scala.html
The framework for requesting JSON backed up by the local storage.
=> Local Storage Request

.travis.yml, Dockerfile, startup.sh
This PR changes the docker file to
- add figure folders
- remove running tests on docker container startup
- partially address #414
=> Docker changes

app/assets/javascripts/abstract-list.js, app/assets/javascripts/abstracts-favourite.js, app/assets/stylesheets/layout.less, app/controllers/Application.scala, app/controllers/api/Abstracts.scala, app/controllers/api/Conferences.scala, app/models/Abstract.scala, app/models/Account.scala, app/service/AbstractService.scala, app/service/ConferenceService.scala, app/utils/RoutesResolver.scala, app/utils/serializer.scala, app/views/abstractlist.scala.html, app/views/dashboard/favouriteabstracts.scala.html, app/views/template.scala.html, conf/routes, test/service/Assets.scala, test/util/serializer/SerializerTest.scala
This PR merges the "Favourite abstract" branch (see PR #416) into master. These changes involve updates of the database schema. The update has been tested with the new docker deployment and has worked without any deployment issues.
=> Favorite Abstracts

app/assets/javascripts/admin-conference.js, app/assets/javascripts/editor.js, app/assets/javascripts/userdash.js, app/controllers/api/Conferences.scala, app/views/submission.scala.html
This PR fixes some minor issues when creating/updating abstracts and conferences.
=> Abstract and Conference Errors

.gitignore, app/assets/javascripts/admin-conference.js, app/assets/javascripts/conference-list.js, app/assets/javascripts/lib/models.js, app/controllers/api/Banners.scala, app/models/Banner.scala, app/models/Conference.scala, app/service/BannerService.scala, app/service/ConferenceService.scala, app/utils/RoutesResolver.scala, app/utils/serializer.scala, app/views/conference.scala.html, app/views/conferencelist.scala.html, app/views/dashboard/admin/conference.scala.html, conf/application.conf, conf/routes, test/service/Assets.scala
This pull request adds the ability to upload conference graphics.
Add a new Banners model
Backend changes to add banners to conference
Frontend: Instead of giving an external link, logos can now be uploaded
=> Conference Graphics Upload

app/assets/javascripts/admin-conference.js, app/assets/javascripts/conference-list.js, app/assets/javascripts/lib/models.js, app/controllers/api/Banners.scala, app/models/Banner.scala, app/utils/serializer.scala, app/views/conference.scala.html, app/views/conferencelist.scala.html, app/views/dashboard/admin/conference.scala.html
This pull request 
- adds a banner type variable to the Conference Banner model
- adds the banner types "logo" and "thumbnail", making them optionally uploadable. Closes #385 .
- Fixes the figure URL definition in models.js
- Clears some minor style issues in admin-conference.js
=> Add Conference Banner Types

app/controllers/Accounts.scala, app/controllers/Application.scala, app/forms/ResetPasswordForm.scala, app/views/changemail.scala.html, app/views/passwordreset.scala.html, app/views/submission.scala.html, test/controller/AccountsCtrlTest.scala
This pull request
- Fixes some minor issues with messages regarding login, signup, password and e-mail changes. Closes #464, #465, #466, #467, #473
- Corrects to the right (logged in) menu bar on passwordchange and changeemail pages. Closes #468.
- Removes the DOI notices when submitting abstract references. Closes #478.
=> User Notifications

.gitignore, test/frontend/Readme.md
This PR updates
- the gitignore file to include python cache folders
- the Selenium Readme file to include information about prerequisites and handling of the local selenium jar file.
=> Readme updates for selenium testing

app/assets/javascripts/editor.js, app/views/submission.scala.html, test/frontend/conftest.py, test/frontend/test_editor.py, test/frontend/test_login.py, test/service/Assets.scala
This Pull Request
- introduces some IDs and Classes in order to render the code more stable and readable.
- solves issues with geckodriver/firefox and moving to elements.
- introduces a general function for motion to elements by class name.
- adds further tests for abstract submission.
- fixes affiliation deletion and closes #494
=> Add Editor Tests

app/assets/javascripts/abstract-list.js, app/views/abstractlist.scala.html
This PR:
- adds a text search field for the conference abstracts list.
- simplifies the code to mark favorite abstracts in the conference abstracts list.
=> Search Abstracts List

Dockerfile, Dockerfile_dependencies, project/plugins.sbt, test/controller/BannerCtrlTest.scala, test/controller/FigureCtrlTest.scala
This PR
- fixes the now required dependency CDNs for a successful build
- adds a layered build to docker to avoid timeouts from the required CDNs
- adds a timeout to figure and banner tests to accommodate test runs on docker hub.
=> Sbt build fix
